name:                Advent2018
version:             0.1.0.0
github:              "agentultra/Advent2018"
license:             MIT
author:              "James King"
maintainer:          "james@agentultra.com"
copyright:           "2018 James King"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Advent2018#readme>

default-extensions:
- NoImplicitPrelude
- OverloadedStrings

dependencies:
- base >= 4.7 && < 5
- protolude
- text

library:
  source-dirs: src
  dependencies:
  - containers
  - lens

executables:
  Day1:
    main:                Main.hs
    source-dirs:         app/Day1
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -j=4
    dependencies:
    - Advent2018
  Day2:
    main:                Main.hs
    source-dirs:         app/Day2
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -j=4
    dependencies:
    - Advent2018

tests:
  Advent2018-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -j=4
    dependencies:
    - Advent2018
    - hspec
